---
title: "Intro RMD"
author: "Mauro Mardones"
output: html_document
date: "2023-02-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# INTRODUCTION

First exercise in `RMD` format to ACD Curse. We can write different format like *italics* or **bolded**

### Set Libraries 

```{r}
library(tidyverse)
library(readr)
```


An example of chunk inside syntax.

```{r}
data(iris)
gplo <- ggplot(iris, aes(Species, Sepal.Width, fill=Species)) +
  geom_boxplot()+
  scale_fill_viridis_d()+
  theme_bw()
gplo

```
Another exercise.

```{r}
library(readr)
library(tidyverse)
data2 <- read_csv("data/byerlySalmonByRegion.csv")
names(data2)
glimpse(data2)
datopi <- data2 %>%
  pivot_longer(cols = c( "Sockeye" , "Coho" ,       
                        "Pink" ,"Chum"), 
               names_to = "Species", values_to = "catch")
names(datopi)
unique(datopi$Species)
as <- ggplot(datopi,
             aes(y=catch, x=Year, 
             colour=Species)) +
  geom_point()+
  scale_colour_viridis_d(option = "A")+
  stat_smooth(method = "loess")+
  facet_wrap(~Region, scales="free_y")+
  theme_bw()+
  xlab("")+
  ylab("")
as
```

